import type { Metadata } from "next";
import {  Poppins,Inter } from "next/font/google";
import "./globals.css";

const poppins =Poppins({
  variable:"--font-poppins",
  weight:["600","500"],
  subsets:["latin"],
  display:"swap"
})

const inter=Inter({
  variable:"--font-inter",
  weight:"600",
  subsets:["latin"],
  display:"swap"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.className} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
